.travis.yml
Makefile
web/react/package.json
web/react/src/components/pf3/Dashboard.tsx
web/react/src/components/pf3/KChart.stories.tsx
web/react/src/components/pf3/KChart.tsx
web/react/src/components/pf4/Dashboard.tsx
web/react/src/components/pf4/KChart.stories.tsx
web/react/src/components/pf4/KChart.tsx
web/react/src/index.ts
web/react/src/types/Dashboards.ts
web/react/src/types/Metrics.ts
web/react/src/types/__mocks__/Charts.mock.ts
web/react/src/utils/__tests__/formatter.test.ts
web/react/src/utils/c3ChartsUtils.ts
web/react/src/utils/formatter.ts
web/react/src/utils/victoryChartsUtils.ts
web/react/tslint.json
web/react/yarn.lock

Copied more or less the rules from kiali's tslint
Up to relax some rules when they're annoying for development

Add tslint (issue #6)

---

business/dashboards.go
model/dashboards.go
web/react/package.json
web/react/src/components/pf3/KChart.tsx
web/react/src/types/Dashboards.ts

Screenshot:
Related JIRA: https://issues.jboss.org/browse/KIALI-2522

KIALI-2522 Supply error in charts model, display in charts

---

web/react/package.json
web/react/src/components/pf3/Dashboard.stories.tsx
web/react/src/components/pf3/KChart.stories.tsx
web/react/src/components/pf4/Dashboard.stories.tsx
web/react/src/components/pf4/KChart.stories.tsx
web/react/src/components/pf4/KChart.tsx
web/react/src/types/__mocks__/Charts.mock.ts
web/react/src/types/__mocks__/Dashboards.mock.ts
web/react/src/utils/__tests__/victoryChartsUtils.test.ts
web/react/src/utils/victoryChartsUtils.ts
web/react/yarn.lock

Also fixed pf3 storybook with correct CSS
Note, it has no impact on Kiali yet

Patternfly 4 update: now looking good

---

web/pf4/src/components/KChart.tsx

**Before** (chart title was in the legend):
**After**:

Move title to top of the chart (issue #17)

---

web/pf3/src/types/__mocks__/Charts.mock.ts
web/pf3/src/utils/__tests__/c3ChartsUtils.test.ts
web/pf3/src/utils/c3ChartsUtils.ts

Similar fix than https://github.com/kiali/kiali-ui/pull/1294
(With updated mock / storybook to illustrate the case)

KIALI-2985 normalize timeseries on X axis

---

web/pf3/yarn.lock
web/pf4/yarn.lock

CVE-2019-10744 (prototype pollution)

Update lodash (fix vuln)

---

web/pf4/package.json
web/pf4/src/components/KChart.stories.tsx
web/pf4/src/components/KChart.tsx
web/pf4/src/types/VictoryChartInfo.ts
web/pf4/src/types/__mocks__/Charts.mock.ts
web/pf4/src/types/__mocks__/Dashboards.mock.ts
web/pf4/src/utils/__tests__/victoryChartsUtils.test.ts
web/pf4/src/utils/victoryChartsUtils.ts
web/pf4/yarn.lock

Also upgrade pf/react-charts to get a bug fix on colors wrongly distributed.

Fix PF4 legend with many items (#37)

---

web/common/utils/timeSeriesUtils.ts
web/pf3/src/components/Dashboard.tsx
web/pf3/src/components/KChart.stories.tsx
web/pf3/src/types/__mocks__/Charts.mock.ts
web/pf3/src/utils/__tests__/c3ChartsUtils.test.ts
web/pf3/src/utils/c3ChartsUtils.ts
web/pf4/src/components/Dashboard.tsx
web/pf4/src/components/KChart.stories.tsx
web/pf4/src/components/KChart.tsx
web/pf4/src/types/__mocks__/Charts.mock.ts
web/pf4/src/utils/__tests__/victoryChartsUtils.test.ts
web/pf4/src/utils/victoryChartsUtils.ts

Tests added, both PF3 and PF4
https://issues.jboss.org/browse/KIALI-3168

KIALI-3168 take function to map labels for pretty display

---

RELEASE.md

I'm adding some comments about releasing when it impacts Kiali.
Does it sound good to you?
This is how I'm proceeding right now.

Add info on releasing w/ kiali

---

business/grafana.go

Same as https://github.com/kiali/kiali/pull/1699

Allow grafana dashboard path without leading slash

---

web/common/types/Dashboards.ts
web/pf4/src/components/KChart.stories.tsx
web/pf4/src/components/KChart.tsx
web/pf4/src/index.ts
web/pf4/src/types/__mocks__/Charts.mock.ts
web/pf4/src/types/__mocks__/Dashboards.mock.ts

With this we can add only the scatter plot, I need this for the Chart for the traces.

Let Dashboard & KChart have a scatter chart

---

web/pf4/src/components/ChartWithLegend.stories.tsx
web/pf4/src/index.ts
web/pf4/src/types/VictoryChartInfo.ts
web/pf4/src/utils/victoryChartsUtils.ts

Also create helper function makeLegend

More exports, fix VCDataPoint type too strict

---

web/pf4/src/components/ChartWithLegend.stories.tsx
web/pf4/src/components/ChartWithLegend.tsx
web/pf4/src/components/CustomFlyout.tsx
web/pf4/src/components/Dashboard.stories.tsx
web/pf4/src/components/Dashboard.tsx
web/pf4/src/components/KChart.tsx
web/pf4/src/types/__mocks__/Charts.mock.ts

Update some stories with that
Fixes https://github.com/kiali/k-charted/issues/15

Allow to force charts displayed on a fixed time window

---

web/pf4/src/components/ChartWithLegend.tsx
web/pf4/src/components/KChart.stories.tsx
web/pf4/src/utils/__tests__/victoryChartsUtils.test.ts
web/pf4/src/utils/victoryChartsUtils.ts

Part of https://github.com/kiali/kiali/issues/2107

Handle clicks on overlay

---

web/pf4/src/components/CustomTooltip.tsx
web/pf4/src/utils/victoryChartsUtils.ts

Fixes https://github.com/kiali/kiali/issues/2238

Fix special symbols in legend & tooltips

---

web/pf4/package.json
web/pf4/yarn.lock

Upgrade PF4 stuff to release 2020.04

---

prometheus/client.go

- It's causing errors in some cases, like at least with empty data
- It's ugly
- We'll assume NaN should not be present in data. If there's NaN in prometheus, it should be investigated why, and fix that root cause.
Fixes https://github.com/kiali/kiali/issues/2818

Remove ugly evictNaN workaround

---

web/pf4/src/components/ChartWithLegend.tsx
web/pf4/src/components/Container.tsx
web/pf4/src/components/KChart.stories.tsx
web/pf4/src/types/Overlay.ts
web/pf4/src/utils/__tests__/victoryChartsUtils.test.ts
web/pf4/src/utils/victoryChartsUtils.ts

- Allow to turn on bucketed display using box plots, when number of buckets is specified
- Add story, tests, more code comments
- Fixing small issue in findClosestDatapoint, changed domain conversion function.
Fixes kiali/kiali#2198

Overlay bucketed display

---

business/dashboards.go
kubernetes/v1alpha1/spec.go
model/dashboards.go
model/dashboards_test.go
prometheus/mock/mock.go

- New chart config in CR: `groupLabels`, `sortLabel` and `sortLabelParseAs`
- + Adding some tests
Fixes https://github.com/kiali/kiali/issues/3023
Fixes https://github.com/kiali/kiali/issues/3022

Default labels grouping and sorting

---

README.md
business/dashboards.go
business/dashboards_test.go
config/config.go
kcharted.go

Fixes https://github.com/kiali/kiali/issues/3055

Make namespace label configurable

---

kubernetes/v1alpha1/spec.go
model/dashboards.go
web/common/types/Dashboards.ts

Fixes https://github.com/kiali/kiali/issues/3047

New 'SingleSelection' config for labels in custom dashboards CR & model

---

web/pf4/package.json
web/pf4/yarn.lock

Just to be on page with https://github.com/kiali/kiali-ui/pull/1927

Patternfly minor bump
