- Makefile
- README.md
- business/dashboards.go
- business/pods.go
- config/config.go
- http/handler.go
- http/helper.go
- model/pod.go
This handler mimics what Kiali does to extract dashboards annotations from pods, without any hard dependency on the k8s Pod model (so, keeps dependencies as light as possible).
> Add new http handler SearchDashboardsHandler

- business/dashboards_test.go
- model/dashboards_test.go
Add tests to make sure we never produce nil-slices before json serialization
See comments in https://issues.jboss.org/browse/KIALI-3069
> Adding more tests (see KIALI-3069)

- business/dashboards.go
- config/config.go
- config/promconfig/promconfig.go
- prometheus/client.go
- prometheus/roundtripper.go
Doing here similar implementation as what was done in Kiali, allowing basic auth, oauth/token, ssl, insecure ...
> KIALI-3050 Allow authenticated access to prometheus

- web/pf4/src/utils/victoryChartsUtils.ts
**Before** (note the Y-axis values unordered, because they are seen as strings):
**After**:
> Convert values explicitely into numbers (issue #24)

- web/pf4/src/utils/__tests__/victoryChartsUtils.test.ts
- web/pf4/src/utils/victoryChartsUtils.ts
Histograms with NaN now look good in Kiali:
> PF4: Filter NaN from y values (#35)

- kubernetes/v1alpha1/spec.go
- model/dashboards.go
- web/common/types/Dashboards.ts
- web/pf4/src/components/KChart.stories.tsx
- web/pf4/src/components/KChart.tsx
Available chart types are 'line', 'area' and 'bar'. Defaults to 'line'.
Y-domain refers to min & max on Y values.
Addresses both #41 and #14
> Allow to specify chart type and y-domain with dashboard spec

- web/common/utils/timeSeriesUtils.ts
- web/pf3/src/utils/__tests__/c3ChartsUtils.test.ts
- web/pf4/src/utils/__tests__/victoryChartsUtils.test.ts
'average' is also shortened to 'avg'.
This is a better fit for large legends.
Fixes #39
> Rename 'quantile 0.xx' => pxx

- web/pf4/src/components/Container.tsx
- web/pf4/src/components/Dashboard.stories.tsx
- web/pf4/src/components/Dashboard.tsx
- web/pf4/src/components/KChart.stories.tsx
- web/pf4/src/components/KChart.tsx
- web/pf4/src/types/__mocks__/Charts.mock.ts
- web/pf4/src/types/__mocks__/Dashboards.mock.ts
- web/pf4/src/utils/victoryChartsUtils.ts
This is a workaround for FormidableLabs/victory#1355
It seems to relate to events sent on behalf of 'parent' svg when charts are being reloaded. The issue was not seen in k-charted / storybook, but in Kiali, probably some racy condition.
Adding several small enhancements at the same time (different commit):
- Fix href warning
- Add story for chart with labels
- Move container creation out of chart
> Workaround for VictoryVoronoiContainer crash 

- README.md
- business/dashboards.go
- business/dashboards_test.go
- business/grafana.go
- config/config.go
- config/extconfig/extconfig.go
- http/handler.go
- httputil/http_util.go
- kcharted.go
- kubernetes/v1alpha1/spec.go
- log/logger.go
- model/dashboards.go
- prometheus/client.go
- web/common/types/Dashboards.ts
- web/pf3/src/index.ts
- web/pf3/src/types/__mocks__/Dashboards.mock.ts
- web/pf4/src/index.ts
- web/pf4/src/types/__mocks__/Dashboards.mock.ts
- Add external links to CR spec
- Manage resolving grafana links, find out path through Grafana API
- Some refactoring on how logger is injected in k-charted
- On frontend, define model matching server model to be consumed (by kiali...)
Part of https://github.com/kiali/kiali/issues/1676
> Manage external links to grafana dashboards within CR

- log/logger.go
- log/logger_test.go
... so that logging at level X fallbacks to log at level x+1 if corresponding adapter is missing
e.g. log.Warningf fallbacks to log.Infof if Warningf callback is missing
Add tests
> Improve logger with missing adapters

- business/dashboards.go
- business/dashboards_test.go
- kubernetes/mock/mock.go
- kubernetes/v1alpha1/spec.go
- model/dashboards.go
- model/dashboards_test.go
E.g. if values are expressed in milliseconds for a given metric, we need to define chart with:
unit: "seconds"
unitScale: 0.001
Unit stands for the *base* unit, regardless scale.
Closes https://github.com/kiali/kiali/issues/1715
> Handle unit scaling when input already scaled

- web/pf4/package.json
- web/pf4/src/components/Container.tsx
- web/pf4/src/components/CustomFlyout.tsx
- web/pf4/src/components/Dashboard.stories.tsx
- web/pf4/src/components/Dashboard.tsx
- web/pf4/src/components/KChart.stories.tsx
- web/pf4/src/components/KChart.tsx
- web/pf4/src/types/VictoryChartInfo.ts
- web/pf4/src/utils/__tests__/victoryChartsUtils.test.ts
- web/pf4/src/utils/victoryChartsUtils.ts
- web/pf4/yarn.lock
Closes https://github.com/kiali/kiali/issues/1648
This is bringing into k-charted the same legend behaviours as what has been added in Kiali's sparklines / side panel bar charts
> Interactive legend on kchart

- web/pf4/src/components/ChartWithLegend.stories.tsx
- web/pf4/src/components/ChartWithLegend.tsx
- web/pf4/src/components/Container.tsx
- web/pf4/src/components/Dashboard.tsx
- web/pf4/src/components/KChart.stories.tsx
- web/pf4/src/components/KChart.tsx
- web/pf4/src/types/Overlay.ts
- web/pf4/src/types/VictoryChartInfo.ts
- web/pf4/src/types/__mocks__/Charts.mock.ts
- web/pf4/src/utils/victoryChartsUtils.ts
- Add ability to display a custom overlay over kchart, as scatter plots
- Add ability to create charts without k-charted models / monitoringdashboard CRD => expose a new component ChartWithLegend for that
- Some refactoring to lighten the KChart component (now using that new ChartWithLegend)
- New stories: one for ChartWithLegend (simulating traces), another for the overlay
- Draw another axis and normalize values (see https://formidable.com/open-source/victory/gallery/multiple-dependent-axes )
Closes https://github.com/kiali/kiali/issues/1939
> Traces via k-charted

- web/pf4/src/components/ChartWithLegend.stories.tsx
- web/pf4/src/components/ChartWithLegend.tsx
- web/pf4/src/components/Dashboard.stories.tsx
- web/pf4/src/components/Dashboard.tsx
- web/pf4/src/components/KChart.stories.tsx
- web/pf4/src/components/KChart.tsx
- web/pf4/src/index.ts
- web/pf4/src/types/Overlay.ts
- web/pf4/src/types/__mocks__/Charts.mock.ts
- web/pf4/src/utils/victoryChartsUtils.ts
- Caller can now provide list of datapoints in victory format
- Expose more classes and methods
- Overlays come hidden at init
- There's now an onclick hook so that caller can interact more deeply with the charts
Part of https://github.com/kiali/kiali/issues/1854
> Overlays: some refactoring to allow more manipulation from caller

- web/pf4/src/components/ChartWithLegend.tsx
- When the overlay is using the same unit as the metrics, and it's roughly at the same order of scaling (less than twice bigger), it will share the same axis as the one for metrics
- Draw overlay before metrics so that it appears "below"
- Set cursor: pointer on legend items
> Overlays: 1 axis when same unit, draw "below" metrics

- .travis.yml
- Makefile
- web/pf4/package.json
- web/pf4/src/components/ChartWithLegend.stories.tsx
- web/pf4/src/components/ChartWithLegend.tsx
- web/pf4/src/utils/__tests__/victoryChartsUtils.test.ts
- web/pf4/src/utils/victoryChartsUtils.ts
- web/pf4/yarn.lock
New algorithm to find closest dp; Added stories & tests
Closes https://github.com/kiali/kiali/issues/2039
> onClick hook: find closest datapoint

- web/pf4/src/components/ChartWithLegend.tsx
This is for k-charted (mostly metrics pages ...)
Fixes https://github.com/kiali/kiali/issues/2069
> Hack - one-pixel domain padding to prevent clipping

- web/pf4/src/components/ChartWithLegend.tsx
Fixes https://github.com/kiali/kiali/issues/2083
**Before**:
*second axis was visible even with overlay hidden*
**After:**
*second axis is hidden when overlay hidden*
> Never show 2nd axis when overlay is not displayed

- web/pf4/src/components/ChartWithLegend.stories.tsx
- web/pf4/src/components/ChartWithLegend.tsx
- web/pf4/src/components/SparklineChart.tsx
- web/pf4/src/utils/events.ts
- web/pf4/src/utils/victoryChartsUtils.ts
Use name instead. So that hidden overlay will not mix up with other series when incoming props & number of series change
Fixes https://github.com/kiali/kiali/issues/2525
Note: there's an API change that needs an update in kiali-ui. To test within kiali, use: https://github.com/kiali/kiali-ui/pull/1695
> Chart legends: do not use index to store hidden series

- web/pf4/src/components/ChartWithLegend.tsx
- web/pf4/src/components/Container.tsx
- web/pf4/src/components/CustomTooltip.tsx
When onclick handler is defined, it must catch clicks through tooltips as well. Else, tooltip would prevent user to catch what is "behind" it.
Fixes https://github.com/kiali/kiali/issues/2527
Can be tested via storybook "ChartWithLegend as scatter plots", clicking on one of the plot where tooltip hides the plot:
> Charts: click through tooltips

- .travis.yml
- business/dashboards.go
- business/dashboards_test.go
- kubernetes/mock/mock.go
- kubernetes/v1alpha1/spec.go
- model/dashboards.go
- model/dashboards_test.go
- prometheus/client.go
- prometheus/mock/mock.go
- web/common/types/Dashboards.ts
- web/common/types/Labels.ts
- web/common/types/Metrics.ts
- web/common/utils/timeSeriesUtils.ts
- web/pf4/src/types/__mocks__/Charts.mock.ts
- web/pf4/src/types/__mocks__/Dashboards.mock.ts
- web/pf4/src/utils/__tests__/victoryChartsUtils.test.ts
- web/pf4/src/utils/victoryChartsUtils.ts
- Changed MonitoringDashboard Spec: new "Metrics" field (list of metrics within a chart)
o Backward-compatible from user point of view (no need to update dashboards)...
o But breaking change from developer point of view, consuming side (Kiali) needs to adapt
- Updated fetching process
- Updated model on front/back interface: removed distinction "metric vs histogram", now there's several metrics and histograms are just a (not-so-)special case of that
- Updated tests, both front and back; updated front stories
Fixes https://github.com/kiali/kiali/issues/1778
> Allow multiple metrics per chart

- web/pf4/src/utils/victoryChartsUtils.ts
Hey @aljesusg , this is a quick follow-up on https://github.com/kiali/k-charted/pull/91 (the one you tested today) where I forgot to add some information about bucket (start / end time).
I need this in order to "zoom" in bucket when it's clicked, in an upcoming Kiali PR
> Add start and end bucket info

- web/pf4/src/components/Container.tsx
- web/pf4/src/components/CustomTooltip.tsx
Fixes https://github.com/kiali/kiali/issues/2930
> Add time info in tooltips

- business/dashboards_test.go
- kubernetes/v1alpha1/spec.go
- model/dashboards.go
- prometheus/mock/mock.go
- web/common/types/Dashboards.ts
- web/pf4/src/components/ChartWithLegend.tsx
- web/pf4/src/components/Container.tsx
- web/pf4/src/components/CustomTooltip.tsx
- web/pf4/src/components/KChart.stories.tsx
- web/pf4/src/components/KChart.tsx
- web/pf4/src/types/__mocks__/Dashboards.mock.ts
- web/pf4/src/utils/victoryChartsUtils.ts
- New "xAxis" field in monitoringdashboard CR under Spec.Charts, which can be either time or series (default=time)
- When this field is "series", chart is forced as bar chart with a couple of specific render options (bar width, domain padding...) and x-axis being linear scale with special tick values
- New stories in storybook: KChart "with x-axis as series" and Dashboard with a chart with x-axis as series
Fixes https://github.com/kiali/kiali/issues/2993
> Allow series-based x-axis

- web/pf4/src/components/ChartWithLegend.tsx
- web/pf4/src/components/Dashboard.tsx
Follow-up on https://github.com/kiali/k-charted/pull/98
- Fixed bar charts overlaping on left axis
- Won't display overlay when xAxis type is series (timeless)
> Fix issues found on x-series charts

- web/pf4/src/components/ChartWithLegend.tsx
Because it's redundant with legend
Fixes https://github.com/kiali/kiali/issues/3077
Screenshot (storybook) :
> Hide x tick labels when xaxis type is 'series'

- web/pf4/src/components/ChartWithLegend.tsx
- web/pf4/src/components/Container.tsx
- web/pf4/src/components/CustomTooltip.tsx
- web/pf4/src/utils/__tests__/victoryChartsUtils.test.ts
- web/pf4/src/utils/events.ts
- web/pf4/src/utils/victoryChartsUtils.ts
Fixes https://github.com/kiali/kiali/issues/3171
Change the click-focus detection: instead of trying to re-compute closest point based on mouse position, data and domain projection, store & retrieve whatever is selected (mouse-over) when tooltip pops up. This method seems much more reliable.
However as a consequence, since clicking now depends on tooltip being displayed, deactivating tooltips would also deactivate onclick hooks. But as of today this is not a problem in Kiali.
> On click handler: use tooltip-focused datapoint

- web/pf4/src/components/ChartWithLegend.stories.tsx
- web/pf4/src/components/ChartWithLegend.tsx
- When ChartWithLegend has props overrideSeriesComponentStyle set to false, it will not try to apply any style (it defaults to true)...
- ... which allows the caller to provide its own style directly in the seriesComponent props
- Example of use in storybook "ChartWithLegend > with style override"
Storybook:
> Provide better control over styles

- web/pf4/src/components/KChart.tsx
Fixes https://github.com/kiali/kiali/issues/3307
Before:
```
margin-bottom: -3.5em; margin-right: 0.8em; top: -2.7em; z-index: 1; position: relative; float: right;
```
After:
```
margin-bottom: -3.5em; margin-right: 0.8em; top: -2.7em; position: relative; float: right;
```
Storybook seems without side effects:
> Wrong z-index for refresh controller

- README.md
Note, I don't think we should archive this repository right now (ie. make it read-only) as it's still used in some previous versions of kiali that are, if I'm correct, still under support.
> README: mention discontinued project
